### ISSUE TITLE
Node-gyp rebuild

### ISSUE THREAD

**Issue by TomVerhoeven** [malithsen/playmyway#1]
Thanks for the great work Mailith, Hasanga and Sisinda! The project seems very interesting to me. When trying to install it, I encountered a problem. Maybe you can help me out. I am using Ubuntu Server 16.04, but I could use something else as well. Please find the output below.

```
~/playmyway$ npm install --no-optional

> speaker@0.2.6 install /home/tom/playmyway/node_modules/speaker
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tom/playmyway/node_modules/speaker
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
PlayMyWay@0.0.1 /home/tom/playmyway
└── (empty)

npm WARN PlayMyWay@0.0.1 No repository field.
npm WARN PlayMyWay@0.0.1 No license field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-optional"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tom/playmyway/npm-debug.log
npm ERR! code 1
```

**Comment by hasa93** [comment]
Hey Tom,
Glad you like the project! it seems like the build is failing on npm speaker module. Since you are on Ubuntu you might need to install ALSA headers if they aren't already in place. Did you try `sudo apt-get install libasound2-dev` before `npm install`?

**Comment by TomVerhoeven** [comment]
Hi Hasanga,

Thank you so much for the quick reply! Yes, I did install the ALSA headers. I am also using a fresh virtual machine to increase the chance on a successful installation. Do you maybe have additional ideas I can give a try? Thanks!

Kind regards,
Tom

**Comment by dinush** [comment]
Hi Tom,

Try this,
`sudo ln -s /usr/bin/nodejs /usr/bin/node`
